server:
  port: 8282
spring:
  application:
    name: service-mq
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    username: root
#    password: root
#    url: jdbc:mysql://192.168.200.128:3306/gmall_user?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.200.128
    port: 6379
    database: 0
  rabbitmq:
    host: 192.168.200.128
    port: 5672
    username: guest
    password: guest
#    开启监听模式
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
#        开启手动确认每次更新一条
        acknowledge-mode: manual
        prefetch: 1
# mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
feign:
  client:
    config:
      default:
        readTimeout: 600000
        connectTimeout: 600000