server:
  port: 8208
spring:
  application:
    name: service-user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.200.128:3306/gmall_user?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.200.128
    port: 6379
    database: 0
# mybatis
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*Mapper.xml
feign:
  client:
    config:
      default:
        readTimeout: 600000
        connectTimeout: 600000