server:
  port: 8202
spring:
  application:
    name: service-item
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
  redis:
    host: 192.168.200.128
    port: 6379
    database: 0
feign:
  client:
    config:
      default:
        readTimeout: 600000
        connectTimeout: 600000