server:
  port: 8203
spring:
  application:
    name: service-list
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://192.168.200.128:3306/gmall_product?characterEncoding=utf-8&useSSL=false
  redis:
    host: 192.168.200.128
    port: 6379
    database: 0
  elasticsearch:
    rest:
      uris: http://192.168.200.128:9200
feign:
  client:
    config:
      default:
        readTimeout: 600000
        connectTimeout: 600000